/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: schema.json
export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type ArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "article";
};

export type ExperienceRole = {
  _type: "experienceRole";
  role?: string;
  period?: string;
  employmentType?: string;
  isCurrent?: boolean;
  tags?: Array<string>;
  note?: string;
  relatedWork?: ArrayOf<ProjectReference | ArticleReference>;
};

export type AwardEntry = {
  _type: "awardEntry";
  title?: string;
  org?: string;
  location?: string;
  period?: string;
};

export type EducationEntry = {
  _type: "educationEntry";
  degree?: string;
  school?: string;
  period?: string;
  isCurrent?: boolean;
  status?: string;
  note?: string;
};

export type ProjectMetric = {
  _type: "projectMetric";
  label?: string;
  value?: string;
  progress?: number;
};

export type ExperienceOrg = {
  _id: string;
  _type: "experienceOrg";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company?: string;
  period?: string;
  isCurrent?: boolean;
  location?: string;
  logoUrl?: string;
  roles?: Array<
    {
      _key: string;
    } & ExperienceRole
  >;
  sortOrder?: number;
};

export type TechItem = {
  _id: string;
  _type: "techItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  iconUrl?: string;
  showOnHome?: boolean;
  sortOrder?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type TechItemReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "techItem";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  externalUrl?: string;
  cardDescription?: string;
  tags?: Array<string>;
  imageUrl?: string;
  imageAlt?: string;
  imageWidth?: number;
  imageHeight?: number;
  icon?: string;
  tasks?: Array<string>;
  tech?: Array<
    {
      _key: string;
    } & TechItemReference
  >;
  dossier?: Array<string>;
  metric?: ProjectMetric;
  sortOrder?: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  category?: "Web" | "Web3" | "Fintech" | "Healthcare";
  role?: string;
  link?: string;
  cardDescription?: string;
  tags?: Array<string>;
  imageUrl?: string;
  imageAlt?: string;
  imageWidth?: number;
  imageHeight?: number;
  imageTone?: "dark" | "light";
  videoUrl?: string;
  icon?: string;
  tasks?: Array<string>;
  tech?: Array<
    {
      _key: string;
    } & TechItemReference
  >;
  dossier?: Array<string>;
  metric?: ProjectMetric;
  sortOrder?: number;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  subtitle?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  education?: Array<
    {
      _key: string;
    } & EducationEntry
  >;
  awards?: Array<
    {
      _key: string;
    } & AwardEntry
  >;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  displayName?: string;
  role?: string;
  location?: string;
  mission?: string;
  employerLabel?: string;
  employerUrl?: string;
  featuredProjects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ProjectReference
  | ArticleReference
  | ExperienceRole
  | AwardEntry
  | EducationEntry
  | ProjectMetric
  | ExperienceOrg
  | TechItem
  | Slug
  | TechItemReference
  | Article
  | Project
  | AboutPage
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../sanity/queries.ts
// Variable: PORTFOLIO_QUERY
// Query: {  "settings": *[_id == "siteSettings"][0]{    _updatedAt,    displayName,    role,    location,    mission,    employerLabel,    employerUrl,    featuredProjects[]->{      _id,      _type,      _updatedAt,      name,      title,      "slug": slug.current,      category,      role,      link,      externalUrl,      imageUrl,      imageAlt,      imageWidth,      imageHeight,      imageTone,      videoUrl,      icon,      cardDescription,      tags,      tasks,      dossier,      "tech": tech[]->name,      links[]{label, url},      metric,      sortOrder    }  },  "about": *[_id == "aboutPage"][0]{    _updatedAt,    subtitle,    body,    education[]{      _key,      degree,      school,      period,      isCurrent,      status,      note    },    awards[]{      _key,      title,      org,      location,      period    }  },  "techStack": *[_type == "techItem" && showOnHome == true] | order(sortOrder asc){    _updatedAt,    name,    iconUrl  },  "works": *[_type in ["project", "article"]] | order(sortOrder asc){    _id,    _type,    _updatedAt,    name,    title,    "slug": slug.current,    category,    role,    link,    externalUrl,    imageUrl,    imageAlt,    imageWidth,    imageHeight,    imageTone,    videoUrl,    icon,    cardDescription,    tags,    tasks,    dossier,    "tech": tech[]->name,    links[]{label, url},    metric,    sortOrder  },  "experience": *[_type == "experienceOrg"] | order(sortOrder asc){    _updatedAt,    company,    period,    isCurrent,    location,    logoUrl,    roles[]{      _key,      role,      period,      employmentType,      isCurrent,      tags,      note,      "projects": relatedWork[]->slug.current    }  }}
export type PORTFOLIO_QUERY_RESULT = {
  settings:
    | {
        _updatedAt: string;
        displayName: null;
        role: null;
        location: null;
        mission: null;
        employerLabel: null;
        employerUrl: null;
        featuredProjects: null;
      }
    | {
        _updatedAt: string;
        displayName: null;
        role: string | null;
        location: null;
        mission: null;
        employerLabel: null;
        employerUrl: null;
        featuredProjects: null;
      }
    | {
        _updatedAt: string;
        displayName: null;
        role: null;
        location: string | null;
        mission: null;
        employerLabel: null;
        employerUrl: null;
        featuredProjects: null;
      }
    | {
        _updatedAt: string;
        displayName: string | null;
        role: string | null;
        location: string | null;
        mission: string | null;
        employerLabel: string | null;
        employerUrl: string | null;
        featuredProjects: Array<{
          _id: string;
          _type: "project";
          _updatedAt: string;
          name: string | null;
          title: null;
          slug: string | null;
          category: "Fintech" | "Healthcare" | "Web" | "Web3" | null;
          role: string | null;
          link: string | null;
          externalUrl: null;
          imageUrl: string | null;
          imageAlt: string | null;
          imageWidth: number | null;
          imageHeight: number | null;
          imageTone: "dark" | "light" | null;
          videoUrl: string | null;
          icon: string | null;
          cardDescription: string | null;
          tags: Array<string> | null;
          tasks: Array<string> | null;
          dossier: Array<string> | null;
          tech: Array<string | null> | null;
          links: null;
          metric: ProjectMetric | null;
          sortOrder: number | null;
        }> | null;
      }
    | null;
  about:
    | {
        _updatedAt: string;
        subtitle: null;
        body: null;
        education: null;
        awards: null;
      }
    | {
        _updatedAt: string;
        subtitle: string | null;
        body: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        education: Array<{
          _key: string;
          degree: string | null;
          school: string | null;
          period: string | null;
          isCurrent: boolean | null;
          status: string | null;
          note: string | null;
        }> | null;
        awards: Array<{
          _key: string;
          title: string | null;
          org: string | null;
          location: string | null;
          period: string | null;
        }> | null;
      }
    | null;
  techStack: Array<{
    _updatedAt: string;
    name: string | null;
    iconUrl: string | null;
  }>;
  works: Array<
    | {
        _id: string;
        _type: "article";
        _updatedAt: string;
        name: null;
        title: string | null;
        slug: string | null;
        category: null;
        role: null;
        link: null;
        externalUrl: string | null;
        imageUrl: string | null;
        imageAlt: string | null;
        imageWidth: number | null;
        imageHeight: number | null;
        imageTone: null;
        videoUrl: null;
        icon: string | null;
        cardDescription: string | null;
        tags: Array<string> | null;
        tasks: Array<string> | null;
        dossier: Array<string> | null;
        tech: Array<string | null> | null;
        links: null;
        metric: ProjectMetric | null;
        sortOrder: number | null;
      }
    | {
        _id: string;
        _type: "project";
        _updatedAt: string;
        name: string | null;
        title: null;
        slug: string | null;
        category: "Fintech" | "Healthcare" | "Web" | "Web3" | null;
        role: string | null;
        link: string | null;
        externalUrl: null;
        imageUrl: string | null;
        imageAlt: string | null;
        imageWidth: number | null;
        imageHeight: number | null;
        imageTone: "dark" | "light" | null;
        videoUrl: string | null;
        icon: string | null;
        cardDescription: string | null;
        tags: Array<string> | null;
        tasks: Array<string> | null;
        dossier: Array<string> | null;
        tech: Array<string | null> | null;
        links: null;
        metric: ProjectMetric | null;
        sortOrder: number | null;
      }
  >;
  experience: Array<{
    _updatedAt: string;
    company: string | null;
    period: string | null;
    isCurrent: boolean | null;
    location: string | null;
    logoUrl: string | null;
    roles: Array<{
      _key: string;
      role: string | null;
      period: string | null;
      employmentType: string | null;
      isCurrent: boolean | null;
      tags: Array<string> | null;
      note: string | null;
      projects: Array<string | null> | null;
    }> | null;
  }>;
};

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  "settings": *[_id == "siteSettings"][0]{\n    _updatedAt,\n    displayName,\n    role,\n    location,\n    mission,\n    employerLabel,\n    employerUrl,\n    featuredProjects[]->{\n      _id,\n      _type,\n      _updatedAt,\n      name,\n      title,\n      "slug": slug.current,\n      category,\n      role,\n      link,\n      externalUrl,\n      imageUrl,\n      imageAlt,\n      imageWidth,\n      imageHeight,\n      imageTone,\n      videoUrl,\n      icon,\n      cardDescription,\n      tags,\n      tasks,\n      dossier,\n      "tech": tech[]->name,\n      links[]{label, url},\n      metric,\n      sortOrder\n    }\n  },\n  "about": *[_id == "aboutPage"][0]{\n    _updatedAt,\n    subtitle,\n    body,\n    education[]{\n      _key,\n      degree,\n      school,\n      period,\n      isCurrent,\n      status,\n      note\n    },\n    awards[]{\n      _key,\n      title,\n      org,\n      location,\n      period\n    }\n  },\n  "techStack": *[_type == "techItem" && showOnHome == true] | order(sortOrder asc){\n    _updatedAt,\n    name,\n    iconUrl\n  },\n  "works": *[_type in ["project", "article"]] | order(sortOrder asc){\n    _id,\n    _type,\n    _updatedAt,\n    name,\n    title,\n    "slug": slug.current,\n    category,\n    role,\n    link,\n    externalUrl,\n    imageUrl,\n    imageAlt,\n    imageWidth,\n    imageHeight,\n    imageTone,\n    videoUrl,\n    icon,\n    cardDescription,\n    tags,\n    tasks,\n    dossier,\n    "tech": tech[]->name,\n    links[]{label, url},\n    metric,\n    sortOrder\n  },\n  "experience": *[_type == "experienceOrg"] | order(sortOrder asc){\n    _updatedAt,\n    company,\n    period,\n    isCurrent,\n    location,\n    logoUrl,\n    roles[]{\n      _key,\n      role,\n      period,\n      employmentType,\n      isCurrent,\n      tags,\n      note,\n      "projects": relatedWork[]->slug.current\n    }\n  }\n}': PORTFOLIO_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
